### PR TITLE
Fix bash template for Debian

### PR DESCRIPTION
**Pull request by mhgoldman**
We had updated the bash template to run on Debian rather than Alpine to reflect the pre-cached templates available on the Script Host, but missed the distro-specific changes required. 

The tricky thing here is the availability of `jq` and `curl` which are required by the sample code. Installing these on the fly with `apk` in Alpine was tolerable because it's pretty fast. But `apt` is slow enough that I didn't feel it was acceptable, adding almost 10 seconds to script execution. So I just added statically compiled binaries for the 2 utilities directly into the template. I also had to copy in the SSL certificates, which I grabbed from Debian's `ca-certificates` package.

The "correct" solution would of course be to add these dependencies directly to the image. We could consider doing that later, but it would require us to re-host the base images publicly so they're available to the `bin/run` tool for running locally (in addition to requiring a new Script Host and additional changes to this template). In the meantime, please let me know what you think.

### CODE REVIEW

**Comment by maxwellbooth** [comment]
What would you think about including the ca-certificates deb package as a single file in the the script template and then using dpkg to install it? That might take a little bit longer to set up but it should be much quicker than apt and would be easy to manage as a dependency than 250+ files. We could probably do the same for jq and curl but those bother me less since they are individual binary files that don't clog up the commit history.

**Comment by mhgoldman** [comment]
Thanks @maxwellbooth - I did think about using deb packages and it'd be nice if that would've worked for everything. But there would be about 18 packages required to support jq and curl (including the certificates). That didn't seem like a huge win to me, but it could be done.

I do see your point about the certs in particular creating a bunch of clutter in the zip file. The certs package depends on openssl, so I'd have to install that too. Actually, you can probably just extract the files without properly installing the package, and then the dependencies wouldn't matter... but at that point, why mess with the package at all over throwing them into a zip file, or even just leaving them in the directory structure like I did? Is there an actual benefit? I'm not sure.

**Comment by maxwellbooth** [comment]
@mhgoldman ok that makes sense. thanks.

**Review by maxwellbooth — APPROVED** [review]

**Comment by mhgoldman** [comment]
@maxwellbooth Silly me. Turns out all those individual cert files aren't needed at all, there's a single bundle file that'll suffice. Cleaned up and submitted for rereview.

**Review by maxwellbooth — APPROVED** [review]
looks good 👍

**Pull request merged**
